name: fx_analysis
description: "Use this app to monitor your trading activity"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.2
  provider: ^6.0.1
  fl_chart: ^0.69.0
  uuid: ^3.0.4
  shared_preferences: ^2.0.11
  url_launcher: ^6.1.6
  fixnum: ^1.1.1
  protobuf: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/json/accounts.json
    - lib/json/users.json
    - lib/assets/chart.png

dev_dependencies:
  flutter_lints: ^3.0.0